# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MFPictureBrowserDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MFPictureBrowserDemo
pod ‘YYWebImage’
pod 'YYImage/WebP'
pod ‘MFCategory’
end
